### ISSUE TITLE
Issue in hint

### ISSUE THREAD

**Issue by mitchkeller** [dcernst/IBL-AbstractAlgebra#156]
I ran into this two years ago, and I'm 99.99% certain that I'm right in only seeing how to do this when considering h^{m/p^a}, rather than h^{m/p^b} as written now. (I'm sure there are other ways to rework the hint, but this seems the cleanest.) 

https://github.com/dcernst/IBL-AbstractAlgebra/blob/569bc246573ec22782fa751d88b1f9651f681668/ConstructionZone/Families.tex#L361

**Comment by dcernst** [comment]
I'm pretty sure I agree.  I just made the change. Pushing now.
